### ISSUE TITLE
(BUG WidgetCase version 1.1.1 ) The Share button does not work

### ISSUE THREAD

**Issue by friendsmobile** [faith-hb/WidgetCase#3]
# Project Information

* Repository:  https://github.com/faith-hb/WidgetCase
* Project Name:  WidgetCase
* My Github Account: https://github.com/friendsmobile
* Download the application:   https://github.com/faith-hb/WidgetCase/releases

# Expected behavior

When I click on the share option, all social media should appear next to where I can share this application.

# Actual behavior

When I click on the share option, no application response is encountered

#### How to reproduce

* [Download ](https://github.com/faith-hb/WidgetCase/releases)the application
*  open the application
* at Top Lift side click on 3 horizontal dots 
* click on Share option
* Note the Error

* Browser/App version:  1.1.1
* Operating system: 6.0

#### Recording Of The Bug

![20190725_152807](https://user-images.githubusercontent.com/51118734/61867621-7bf7c280-ae8c-11e9-9a53-7f6e4b1f38f4.gif)

**Comment by faith-hb** [comment]
Sorry, the functions of these two buttons are not yet available. They are pre-realized functions

**Comment by friendsmobile** [comment]
okay dear
